- name: Copying Logstash Config File.
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Stopping Logstash.
  systemd:
    name: logstash
    state: stopped
    
- name: Waiting for Port 5400 to stop.
  wait_for:
    port: 5044
    delay: 15
    state: stopped
    
