- name: Copying Logstash Config File.
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Stopping Logstash.
  systemd: 
    name: logstash
    state: stopped
    
- name: Waiting for 5044 port to stop.
  wait_for:
    port: 5044
    delay: 10
    state: stopped
    

- name: Starting Logstash.
  systemd: 
    name: logstash
    state: startedS
    
- name: Waiting for port 5044 to start.
  wait_for:
    port: 5044
    delay: 10
    state: started

