- name: Setting Up MongoDB repository
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    
- name: Installing MongoDB
  yum:
    name: mongodb-org
    state: present
    
- name: Updating MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    
- name: Starting MongoDB
  systemd:
    name: mongod
    state: restarted
    enabled: yes
    
- name: Downlaoding MongoDB zip file
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes
    
- name: Uploading catalogue Schema into MongoDB
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes
    
- name: Uploading users Schema into MongoDB
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes
