- name: Demo on Variables
  hosts: all
  vars:
    URL1: play.google.com
  vars_files:
    - vars.yml
  roles:
    - sample
  tasks:
    - name: Play level Variables
      debug:
        msg: URL = {{URL1}}
    - name: Variables from files
      debug: 
        msg: URL = {{URL2}}
    - name: Task level variables
      vars:
        URL3: task.google.com
      debug:
        msg: URL = {{URL3}}
    - name: Varibles in Inventory File
      debug: 
        msg: URL = {{URL4}}
    - name: CLI variables
      debug: 
        msg: URL = {{URL5}}
    