- name: Creating Roboshop App user
  user:
    name: roboshop
  register: ROBOSHOP_USER
  when: APP_TYPE == "backend"
    
- name: Removing old file
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent
    
- name: Creating the APP Path for backend
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "backend"
  become_user: roboshop
  
- name: Creating the APP Path for backend
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory
  when: APP_TYPE == "frontend"
  
- name: Copying Azure Repo file
  copy:
    src: az.repo
    dest: /etc/yum.repos.d/
    
#- name: Installing AZ CLI
#  yum:
#    name: [azure-cli]
#    state: present

- name: Installing AZ CLI
  shell: sudo yum install azure-cli -y --skip-broken
  
- name: exit
  shell: exit 1
    
- name: Downloading content from Azure Artifacts
  shell: az artifacts universal download --organization "https://dev.azure.com/dasarisaikrishna97/" --project "54339e52-4014-4697-b8af-f4bd001b418a" --scope project --feed "WS" --name "${COMPONENT}" --version "1.0.0" --path .