- name: Including GitHub Dowloaded Files
  include_tasks: download-from-githud.yml
  when: APP_VERSION == "null"
  
- name: Including GitHub Dowloaded Files
  include_tasks: download-from-nexus.yml
  when: APP_VERSION != "null"