- name: Creating Roboshop App user
  user:
    name: roboshop
  register: ROBOSHOP_USER
  when: APP_TYPE == "backend"
    
- name: Downlaoding {{COMPONENT}} zip file
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes
    
- name: Removing old file
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent
    
- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop
  when: APP_TYPE == "backend"
  
- name: Copying extracted content to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: "{{APP_PATH}}/"
    remote_src: yes
  when: APP_TYPE == "frontend"