- name: Installing Maven
  yum: 
    name: maven
    state: present
    
- name: Dowloading Files
  include_tasks: download.yml
  
- name: Making Maven Package
  shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args: 
    chdir: /home/roboshop/{{COMPONENT}}
    
- name: Configuring systemd
  include_tasks: systemd.yml
  
- name: Updating Rsyslog Configuration.
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf
    
- name: Restarting Rsyslog.
  systemd:
    name: rsyslog
    state: restarted
  
- name: Includling Node_Exporter
  include_tasks: node_exporter.yml

- name: Includling FileBeat
  include_tasks: filebeat.yml
  vars: 
    OUTPUT_TO: logstash
    JAVA: true