- name: Configuring Systemd services
  template: 
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    
- name: Starting {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    #enabled: yes
    daemon_reload: yes