route:
  group_by: ['High_CPU_Usage']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: email
    email_configs:
      - to: dasarisaikrishna97@gmail.com
        from: dasarisaikrishna97@gmail.com
        smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: {{userid}}
        auth_password: {{password}}
        require_tls: yes
        send_resolved: yes
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

