groups:
- name: Instance Resources
  rules:
  - alert: High_CPU_Usage
    expr: cpu_usage_in_percentage > 60
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: High_CPU_Usage in {%raw%}{{ $labels.instance }}{%endraw%}
    
    