global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#roboshop'
        send_resolved: true
        text: {%raw%}"<!channel> \nsummary: {{ .CommonAnnotations.summary }}"{%endraw%}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

