groups:
  - name: HardwareResources
    rules:
      - alert: High_CPU_Usage
        expr: cpu_usage_in_percentage > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High_CPU_Usage on {%raw%}{{ $labels.tagName }}{%endraw%}\nEnv: DEV"
          
  - name: HardwareResources
    rules:
      - alert: High_Memory_Usage
        expr: memory_usage_in_percentage > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High_Memory_Usage on {%raw%}{{ $labels.tagName }}{%endraw%}\nEnv: DEV"
          
          