global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['High_CPU_Usage']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
  slack_configs:
  - channel: '#random'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['High_CPU_Usage', 'dev', 'instance']

