groups:
- name: Instance Resources
  rules:
  - alert: High_CPU_Usage
    expr: cpu_usage_in_percentage > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High_CPU_Usage in {%raw%}{{ $labels.instance }}{%endraw%}
    
    