groups:
  - name: CPU_Resources
    rules:
      - alert: High_CPU_Usage
        expr: cpu_usage_in_percentage > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High_CPU_Usage on {%raw%}{{ $labels.instance }}{%endraw%}"
          
  - name: MemoryResources
    rules:
      - alert: High_Memory_Usage
        expr: memory_usage_in_percentage > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High_Memory_Usage on {%raw%}{{ $labels.instance }}{%endraw%}"
          
  - name: ServiceCheck
    rules:
      - alert: ServiceDown
        expr: node_systemd_unit_state{name=~"(catalogue|cart|nginx|payment|shipping|payment|user).service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service_Down on {%raw%}{{ $labels.instance }}{%endraw%}"