groups:
  - name: Recorded Qurey
    rules:
      - record: cpu_usage_in_percentage
        expr: 100 - (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100

  - name: Recorded Qurey
    rules:
      - record: memory_usage_in_percentage
        expr: (node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes) * 100 / node_memory_MemTotal_bytes

